logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always
  #---
  # TODO Append connection to DB
  #---
  #config:
  #  activate:
  #    on-profile: ci,test
  datasource:
    url: jdbc:h2:mem:shareit
    username: root
    password: root
    driverClassName: org.h2.Driver

  


